### ISSUE TITLE
Is README obsolete?

### ISSUE THREAD

**Issue by chenchix** [edgexfoundry/core-domain-go#13]
There is no code in root directory so go install is failing, I see that models and enum are being used in other places so maybe it is a README typo

**Comment by spencerbull** [comment]
Yes the README is out of date. [core-domain-go](https://github.com/edgexfoundry/core-domain-go) is just a dependency for the other edgex-go microservices. PR should be in soon with an updated README.

**Comment by chenchix** [comment]
Ok, thank you.

Closing issue :)

**Comment by spencerbull** [comment]
@chenchix README has been updated on library usage in PR #14
